### ISSUE TITLE
Intent to reuse your great work here

### ISSUE THREAD

**Issue by codepoke-kk** [richyliu/greggdict#14]
Thank you for all this work, freely offered to the public. I can only imagine the hours this represents. 

I hope to take your Anni json and image files, and build them into the coaching function over at https://github.com/codepoke-kk/qwertigraphy. I wish I could say your work would see the light of day, due to my efforts, but I have not found anyone else interested in it. 

If all goes to plan, any time I enter a new word into the dictionary, I'll be able to click a button to see the dictionary page that has that word. This will help me to be sure I'm always adding the right Gregg pen strokes to my dictionary to correctly render it in the Coach function.

**Comment by richyliu** [comment]
Sounds exciting! Do let me know if you end up making something cool with this, I’d love to check it out.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: codepoke-kk ***@***.***>
Sent: Wednesday, May 24, 2023 5:05:37 PM
To: richyliu/greggdict ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [richyliu/greggdict] Intent to reuse your great work here (Issue #14)


Thank you for all this work, freely offered to the public. I can only imagine the hours this represents.

I hope to take your Anni json and image files, and build them into the coaching function over at https://github.com/codepoke-kk/qwertigraphy. I wish I could say your work would see the light of day, due to my efforts, but I have not found anyone else interested in it.

If all goes to plan, any time I enter a new word into the dictionary, I'll be able to click a button to see the dictionary page that has that word. This will help me to be sure I'm always adding the right Gregg pen strokes to my dictionary to correctly render it in the Coach function.

**Comment by codepoke-kk** [comment]
It happened. :-) 

As I said, it's wrapped up in a Gregg tool only I use. I've introduced it to dozens of people, and none ended up having an interest. I don't demo how it saves me ~40% of my typing by allowing me to type in Gregg briefs instead of in longkey text. But if you imagine I type 6k characters of briefs and 10k characters of words come out, then you can imagine I need to add dictionary definitions for new words all the time. 

I'm using your tool to accelerate the process of adding dictionary words. For the last 2 years I've added words by carrying the Gregg Anni Dictionary back and forth between my different computers and flipping through it for each word. Your tool makes that a 3-click process. 

https://www.youtube.com/watch?v=K7-sZdYJU2s

**Comment by richyliu** [comment]
Very cool! I had a similar idea I while back but I couldn't think of how to represent similar written strokes ("up" `th` for "the" vs "down" `th` for "their") and blended strokes (`d-n` for "down" vs `dn` blend for "ten").

I'm glad this tool helped you out!
